language: perl

notifications:
    recipients:
        - shubina@reg.ru


perl:
    - "5.21"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - "dzil authordeps --missing | xargs cpanm -q -n && dzil listdeps --missing | xargs cpanm -q -n"

script:
    - "dzil smoke"
